### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [NationalSecurityAgency/qgis-searchlayers-plugin#1]
It is apparently very similar to QuickFind. Please consider mergin your plugin to that one, so to avoid plugin duplication and possible confusion for users.

**Comment by hamiltoncj** [comment]
Quick Finder seems it be for searching content from web resources which is great, but we want an in depth search capability for just the vector layers loaded in QGIS. I don't think Quick Finder has the same goal as what we are looking at.

**Comment by pcav** [comment]
Yes, it can also search local or db files. Please see its config.

**Comment by hamiltoncj** [comment]
Yes, but it is very awkward to search local layers and it doesn't search across all fields and all layers without a lot of configuration. I don't think it is meant to be the same type of search capability. I certainly wouldn't want to use their method of searching in layers. My plugin more closely replicates what is done in ArcGIS. I think Quick Finder is great for its nominatim service but not for layer searching.

**Comment by pcav** [comment]
Your argument makes sense to me. Could you please discuss with the developers of QuckFind plugin, better if on qgis-dev mailing list, and check if they are available for a merge or a reduction of functional overlap?
Thanks.

**Comment by hamiltoncj** [comment]
I will see if I can reach out to them although I am not sure how to do that, but I will look around.  I really don't think their plugin is a good match for what I am doing. I wouldn't want this search capability wrapped up in their search as I would be going back and forth turning their settings on and off. I would want the two different search mechanisms as I like their search as it is and I like what I am doing for the intent it is used for. At most they could be collocated, but in that case two plugins would be fine.

**Comment by pcav** [comment]
Again, makes sense to me. Maybe they should remove the duplicated part. Let's see what comes out of the discussion on the mailing list.
Thanks.

**Comment by hamiltoncj** [comment]
I just wanted to reestablish contact with this. I did reach out to the other search developers. The capabilities here simply doesn't match the way "Quick Finder" works. A month or so ago someone asked about this type of functionality. No one else has it like what I have. I pointed this to this plugin, but they had to manually install it.

I think this is worth while having in the QGIS repo. I am told that users can do this type of search in QGIS 3 although I have not found how to do it yet. I know our users will be using QGIS 2.18 for at lease several years so perhaps this will only be for QGIS 2.x.

Note from this initial conversation I renamed the plugin from layersearch to searchlayers since it had never been approved.
